### ISSUE TITLE
Consoder fallback to `js-tiktoken` if failing to import `tiktoken`

### ISSUE THREAD

**Issue by CNSeniorious000** [CNSeniorious000/free-chat#15]
## To-dos:

- [ ] Use [`js-tiktoken`](https://www.npmjs.com/package/js-tiktoken) **at frontend**
- [ ] Slice messages sliding window **at backend**: using [`js-tiktoken`](https://www.npmjs.com/package/js-tiktoken)
- [ ] Cache token counting utilities
- [ ] Standalone tiktoken page
